apiVersion: v1
kind: PersistentVolume
metadata:
  name: girder-src
  namespace: wt
  labels:
    app: girder
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: girder-src
    namespace: wt
  hostPath:
    path: /var/local-path-provisioner/volumes/src
