apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: girder-src
  namespace: wt
  labels:
    app: girder
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 1Gi
