apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: wt
  labels:
    app: registry-docker-registry
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 20Gi
