apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data
  namespace: wt
  labels:
    app: registry-docker-registry
spec:
  storageClassName: manual

  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  claimRef: # the claimRef is here to provide a "connection" between this pv and the pvc.
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: registry-data
    namespace: wt
  hostPath:
    path: /var/local-path-provisioner/volumes/registry
