apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-data
  namespace: wt
  labels:
    app: traefik
spec:
  storageClassName: "manual"

  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  claimRef: # the claimRef is here to provide a "connection" between this pv and the pvc.
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: traefik
    namespace: wt
  hostPath:
    path: /var/local-path-provisioner/volumes/traefik
