apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: gwvolman-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: wholetale/gwvolman@sha256:6c4d362d0ebebee53ea9ecab79a132f1e772be18957634428e62e0d5e5d56894
          env:
            - name: CELERY_BACKEND
              value: {{ .Values.celeryBackend }}
            - name: CELERY_BROKER
              value: {{ .Values.celeryBroker }}
            - name: GOSU_USER
              value: "1000:1000:1001"
            - name: DEPLOYMENT
              value: "k8s"
            - name: DEV
              value: {{ .Values.development | quote }}
            - name: REPO2DOCKER_VERSION
              value: {{ .Values.repo2dockerVersion }}
            - name: DOMAIN
              value: {{ .Values.domain }}
            - name: REGISTRY_USER
              value: {{ .Values.registryUser }}
            - name: REGISTRY_PASS
              value: {{ .Values.registryPass }}
            - name: GIRDERFS_IMAGE
              value: {{ .Values.girderfsImage }}
            - name: GIRDERFS_MOUNT_TYPE
              value: {{ .Values.girderFSMountType }}
            - name: INGRESS_CLASS
              value: {{ .Values.ingressClass }}
            - name: WT_VOLUMES_PATH
              value: {{ .Values.volumesPath }}
            {{- if .Values.mounts.nfs }}
            - name: NFS_SERVER
              value: {{ .Values.mounts.nfs.server }}
            - name: NFS_PATH
              value: {{ .Values.mounts.nfs.path }}
            {{- end }}
          args: ["-Q", "celery,manager"]
          volumeMounts:
            {{- if .Values.development }}
            - name: girder-src
              mountPath: /gwvolman
              subPath: gwvolman
            - name: girder-src
              mountPath: /girderfs
              subPath: girderfs
            {{- end }}
      volumes:
        {{- if .Values.development }}
        - name: girder-src
          persistentVolumeClaim:
            claimName: girder-src
        {{- end }}
