apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: gwvolman-service-account
      imagePullSecrets:
        - name: xarth-dockerhub-creds
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          resources:
            limits:
              cpu: 750m
              ephemeral-storage: 50Mi
              memory: 512Mi
            requests:
              cpu: 700m
              ephemeral-storage: 45Mi
              memory: 512Mi
          env:
            - name: CELERY_BACKEND
              value: {{ .Values.celeryBackend }}
            - name: CELERY_BROKER
              value: {{ .Values.celeryBroker }}
            - name: DEPLOYMENT
              value: "k8s"
            - name: GOSU_USER
              value: "0:0"
            - name: DEV
              value: {{ .Values.development | quote }}
            - name: REPO2DOCKER_VERSION
              value: {{ .Values.repo2dockerVersion }}
            - name: DOMAIN
              value: {{ .Values.domain }}
            - name: REGISTRY_USER
              value: {{ .Values.registryUser }}
            - name: REGISTRY_PASS
              value: {{ .Values.registryPass }}
            - name: GIRDERFS_IMAGE
              value: {{ .Values.girderfsImage }}
            - name: GIRDERFS_MOUNT_TYPE
              value: {{ .Values.girderFSMountType }}
            - name: INGRESS_CLASS
              value: {{ .Values.ingressClass }}
            - name: WT_VOLUMES_PATH
              value: {{ .Values.volumesPath }}
            - name: DOCKER_PULL_SECRET
              value: xarth-dockerhub-creds
            - name: R2D_BASE_IMAGE
              value: {{ .Values.r2dBaseImage }}
            {{- if .Values.mounts.nfs }}
            - name: NFS_SERVER
              value: {{ .Values.mounts.nfs.server }}
            - name: NFS_PATH
              value: {{ .Values.mounts.nfs.path }}
            {{- end }}
          args: ["-Q", "celery,manager", "-c", "3"]
          volumeMounts:
            {{- if .Values.development }}
            - name: girder-src
              mountPath: /gwvolman
              subPath: gwvolman
            - name: girder-src
              mountPath: /girderfs
              subPath: girderfs
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
      volumes:
        {{- if .Values.development }}
        - name: girder-src
          persistentVolumeClaim:
            claimName: girder-src
        {{- end }}
