apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: gwvolman-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: wholetale/gwvolman:k8s
          env:
            - name: CELERY_BACKEND
              value: {{ .Values.celeryBackend }}
            - name: CELERY_BROKER
              value: {{ .Values.celeryBroker }}
            - name: GOSU_USER
              value: "1000:1000:1001"
