apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gwvolman-role-binding
  namespace: {{ .Release.Namespace }} 
subjects:
- kind: ServiceAccount
  name: gwvolman-service-account
  namespace: {{ .Release.Namespace }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: r2d-executor
