apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gwvolman-role-binding
subjects:
- kind: ServiceAccount
  name: gwvolman-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
