service:
  type: NodePort

ports:
  web:
    nodePort: 30000
  websecure:
    nodePort: 30001
    tls:
      enabled: true
      certResolver: "letsencrypt"
      domains:
        - main: "local.wholetale.org"
          sans:
            - "*.local.wholetale.org"

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  annotations: {}

certResolvers:
  letsencrypt:
    email: xarthisius.kk@gmail.com
    dnsChallenge:
      provider: godaddy
      delayBeforeCheck: 1m0s
      resolvers:
        - 1.1.1.1
        - 8.8.8.8
    storage: /data/acme.json

env:
  - name: GODADDY_API_KEY
    value: api
  - name: GODADDY_API_SECRET
    value: secret

ingressRoute:
  dashboard:
    enabled: false

logs:
  general:
    level: DEBUG
