persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  annotations: {}

certResolvers:
  letsencrypt:
    email: xarthisius.kk@gmail.com
    dnsChallenge:
      provider: godaddy
      delayBeforeCheck: 30
      resolvers:
        - 1.1.1.1
        - 8.8.8.8
    storage: /data/acme.json

env:
  - name: GODADDY_API_KEY
    value: api 
  - name: GODADDY_API_SECRET
    value: secret

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
      volumeMounts:
      - mountPath: /data
        name: data

ingressRoute:
  dashboard:
    enabled: false

additionalArguments:
  - --providers.kubernetesingress
  - --certificatesresolvers.godaddy.acme.dnschallenge=true
  - --certificatesresolvers.godaddy.acme.dnschallenge.provider=godaddy
  - --certificatesresolvers.godaddy.acme.dnschallenge.delaybeforecheck=0
  - --certificatesresolvers.godaddy.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
  - --certificatesresolvers.godaddy.acme.dnschallenge.envapi
  - --certificatesresolvers.godaddy.acme.email=xarthisius.kk@gmail.com
  - --certificatesresolvers.godaddy.acme.storage=/data/acme.json
