environments:
  local:
    values:
    - environments/local.yaml
  jhu:
    values:
    - environments/jhu.yaml
  home:
    values:
    - environments/home.yaml

---

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: twuni
    url: https://helm.twun.io

releases:
  - name: mongodb
    namespace: wt
    chart: bitnami/mongodb
    values:
      - values/mongodb-values.yaml.gotmpl

  - name: girder
    namespace: wt
    chart: ./charts/girder
    values:
      - values/girder-values.yaml.gotmpl
    needs:
      - mongodb
      - redis
  
  - name: dashboard
    namespace: wt
    chart: ./charts/dashboard
    values:
      - values/dashboard-values.yaml.gotmpl

  - name: traefik
    installed: {{ eq .Environment.Name "home" | toYaml }}
    namespace: wt
    chart: traefik/traefik
    values:
      - values/traefik-values.yaml.gotmpl

  - name: redis
    namespace: wt
    version: 18.8.2
    chart: bitnami/redis
    values:
      - values/redis-values.yaml

  - name: gwvolman
    namespace: wt
    chart: ./charts/gwvolman
    needs:
      - redis
    values:
      - values/gwvolman-values.yaml.gotmpl

  - name: registry
    namespace: wt
    chart: twuni/docker-registry
    values:
      - values/registry-values.yaml.gotmpl
