repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: mongodb
    namespace: wt
    chart: bitnami/mongodb
    values:
      - values/mongodb-values.yaml

  - name: girder
    namespace: wt
    chart: ./charts/girder
    values:
      - values/girder-values.yaml

  - name: traefik
    namespace: wt
    chart: traefik/traefik
    values:
      - values/traefik-values.yaml
