apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: girder-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: wholetale/girder:k8s
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: {{ .Values.mongodbUri | quote }}
            - name: GIRDER_PORT
              value: "8080"
          args: ["girder", "serve", "--database", {{ .Values.mongodbUri | quote }}]
