apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - "girder.{{ .Values.domain }}"
      - "data.{{ .Values.domain }}"
{{- end }}
  rules:
    - host: "girder.{{ .Values.domain }}"
      http: &backend
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: girder
                port:
                  number: 8080
    - host: "data.{{ .Values.domain }}"
      http: *backend
