apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    keel.sh/policy: all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      priorityClassName: reserved
      serviceAccountName: girder-service-account
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        runAsUser: 101
        runAsGroup: 101
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Always
      containers:
        - name: watcher
          image: xarthisius/dhwatcher:latest
          envFrom:
            - secretRef:
                name: dockerhub-creds
          env:
            - name: POD_NAME
              value: {{ .Chart.Name }}
            - name: POD_NAMESPACE
              value: {{ .Release.Namespace }}
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 100m
              ephemeral-storage: 2Mi
              memory: 256Mi
            requests:
              cpu: 100m
              ephemeral-storage: 1Mi
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
        - name: {{ .Chart.Name }}
          image: xarthisius/iqmcam-docs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Mi
              memory: 256Mi
            requests:
              cpu: 100m
              ephemeral-storage: 1Mi
              memory: 128Mi
          env:
            - name: NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE
              value: "false"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 1
            timeoutSeconds: 10
