kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-data
  namespace: "wt"
  labels:
    app: registry-docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
