celeryBackend: redis://redis-master/
celeryBroker: redis://redis-master/
repo2dockerVersion: xarthisius/repo2docker_wholetale:latest
domain: local.wholetale.org
registryUser: fido
registryPass: secretpass
girderfsImage: wholetale/girderfs:k8s
ingressClass: traefik
girderFSMountType: direct
volumesPath: /srv/data

mounts:
  nfs: {}
